---
- hosts: localhost
  tasks:
    - name: add custom bash_profile to ~/.bash_profile
      lineinfile: dest=~/.bash_profile
                  regexp=".bash_custom"
                  line="if [ -f ~/.bash_custom ]; then . ~/.bash_custom; fi"
                  state=present
